context:
  version: 0.1.3

package:
  name: xeus-ocaml
  version: ${{ version }}

source:
  path: ../

build:
  number: 0

requirements:
  build:
  - ${{ compiler("cxx") }}
  - cmake
  - ninja
  host:
  - nlohmann_json
  - xeus
  - xeus-lite

tests:
- script:
  - test -f $PREFIX/bin/xocaml.wasm
  - test -f $PREFIX/bin/xocaml.js
about:
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: xeus-ocaml
  homepage: https://github.com/davy39/xeus-ocaml
extra:
  recipe-maintainers:
  - Davy39
