// Generated by js_of_ocaml
//# buildInfo:effects=disabled, kind=cma, use-js-string=true, version=6.2.0

//# unitInfo: Provides: Ppx_js_rewriter
//# unitInfo: Requires: Ppx_js
//# unitInfo: Force_link: true
//# shape: Ppx_js_rewriter:[N]
(function
  (globalThis){
   "use strict";
   var runtime = globalThis.jsoo_runtime;
   runtime.jsoo_create_file
    ("/static/cmis/ppx_js_rewriter.cmi",
     'Caml1999I031\x84\x95\xa6\xbe\0\0\0\x81\0\0\0\x14\0\0\0O\0\0\0F\xa0/Ppx_js_rewriter\xa0\xb0\xa0&mapper\x01\x01\x1c\xd0\xc0\xb3\xa1\x90\x92*Ast_mapper&mapper@\x90@\x02\x05\xf5\xe1\0@\0\xfe@\xb0\xc0\t"ppx/ppx_js/lib/ppx_js_rewriter.mliU\x01\x03H\x01\x03H\xc0\x04\x02U\x01\x03H\x01\x03f@@\xa1\x04\x13@@@\x84\x95\xa6\xbe\0\0\x023\0\0\0U\0\0\x01>\0\0\x01\x01\xa0\xa0/Ppx_js_rewriter\x900bzHY<U\xdd\x06hR\xeb\x018U\xb8\x83\xa0\xa0(Warnings\x900\x1c\x10\xe6\0z\xcad\xcd\xa6\x9bk\x05Ue\xb1$\xa0\xa0-Stdlib__Uchar\x900\xc0\xdd\xe0*Ujmy\xe3c\xad6]\x16]W\xa0\xa0+Stdlib__Seq\x900\xb65\x11\x03"\x11\xea\xe4\xb5g\xba1<\xd7)b\xa0\xa0.Stdlib__Lexing\x900\xc91\x8c\'j\xc7\xe3\x83\xfdh,-\xd0k\xe44\xa0\xa0,Stdlib__Lazy\x900\x01C\r4\f\x02\x83"\xc7$p1\xa8t\xe3U\xa0\xa0.Stdlib__Format\x900\xb6\xed\xb9{hX\x19\xe8sH\x1f\xe0W#\xc8\xbc\xa0\xa0.Stdlib__Either\x900&\x84]\xf2\x8d\x19XF\x87\xa3\x8a\x1a\xb8\x14\xc3\xf9\xa0\xa0.Stdlib__Buffer\x900K\t\xc9\xa6\xd0b+\xbfZ8)#KH\x18"\xa0\xa0&Stdlib\x900y\xb0\xe9\xd3\xb6\xf7\xfe\xd0~\xb3\xcc*\xbb\x96\x1b\x91\xa0\xa0)Parsetree\x900\xd1`\xa7\x03\xcc\x0f\xe2\xb0\xa7\xac\xd9\x7fk\xf2RE\xa0\xa0)Longident\x900\xdd\xdb\xcb,x\xe8e\xfdu\xe9\x91\x1cK\x82\xa7\xe2\xa0\xa0(Location\x900\xad\x05\xa1\x1cSP\xa8\x04=\x12\xb4\x81\x95u\xb0;\xa0\xa00CamlinternalLazy\x900Se\xfe\xc4\xa5\x8d\xa3\xe2\xd8\xfa!\x86\xf7}\x9b\xe4\xa0\xa08CamlinternalFormatBasics\x900\x8f\x8fcEXy\x8e\xe4\b\xdf<P\xa5S\x9b\x15\xa0\xa0(Asttypes\x900\xc6\xcb\xda\x07\'\xab$\xf2O\xf7~\x01\x99\x81\x897\xa0\xa0*Ast_mapper\x900J\xa8\xfcIl\xd9Q\xc7G\x0e\xbd\xea\x8d\0f\x13@\x84\x95\xa6\xbe\0\0\0\x04\0\0\0\x02\0\0\0\x05\0\0\0\x05\xa0\x90@@');
   var
    global_data = runtime.caml_get_global_data(),
    Ppx_js = global_data.Ppx_js,
    mapper = Ppx_js[1],
    Ppx_js_rewriter = [0, mapper];
   runtime.caml_register_global(1, Ppx_js_rewriter, "Ppx_js_rewriter");
   return;
  }
  (globalThis));

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoicHB4X2pzX3Jld3JpdGVyLmNtYS5qcyIsInNlY3Rpb25zIjpbeyJvZmZzZXQiOnsibGluZSI6MTAsImNvbHVtbiI6MH0sIm1hcCI6eyJ2ZXJzaW9uIjozLCJmaWxlIjoicHB4X2pzX3Jld3JpdGVyLmNtYS5qcyIsInNvdXJjZXMiOlsiL2J1aWx0aW4vYmxhY2tib3gubWwiXSwic291cmNlc0NvbnRlbnQiOlsiKCogZ2VuZXJhdGVkIGNvZGUgKikiXSwibmFtZXMiOlsicnVudGltZSIsImdsb2JhbF9kYXRhIiwiUHB4X2pzIiwibWFwcGVyIiwiUHB4X2pzX3Jld3JpdGVyIl0sIm1hcHBpbmdzIjoiT0FBQUEsVUFBQTtBQUFBO0FBQUE7QUFBQTtBQUFBO0FBQUEsSUFBQUMsY0FBQTtBQUFBLElBQUFDLFNBQUE7QUFBQSxJQUFBQyxTQUFBO0FBQUEsSUFBQUMsa0JBQUEiLCJpZ25vcmVMaXN0IjpbMF19fV19
